INSERT INTO immunobiological (display,definition) VALUES ('IGHT', 'Imunoglobulina humana antitétano');
INSERT INTO immunobiological (display,definition) VALUES ('SAT', 'Soro antitetânico');
INSERT INTO immunobiological (display,definition) VALUES ('SARC', 'Soro antiaracnídico');
INSERT INTO immunobiological (display,definition) VALUES ('SAESCOR', 'Soro antiescorpiônico');
INSERT INTO immunobiological (display,definition) VALUES ('DT', 'Vacina difteria e tétano infantil');
INSERT INTO immunobiological (display,definition) VALUES ('SAELAP', 'Soro antielapídico');
INSERT INTO immunobiological (display,definition) VALUES ('SAR', 'Soro antirrábico');
INSERT INTO immunobiological (display,definition) VALUES ('SABOTR', 'Soro antibotrópico (pentavalente)');
INSERT INTO immunobiological (display,definition) VALUES ('HepB', 'Vacina hepatite B');
INSERT INTO immunobiological (display,definition) VALUES ('SAD', 'Soro antidiftérico');
INSERT INTO immunobiological (display,definition) VALUES ('SABOCR', 'Soro antibotrópico (pentavalente) e anticrotálico');
INSERT INTO immunobiological (display,definition) VALUES ('SABOLA', 'Soro antibotrópico (pentavalente) e antilaquético');
INSERT INTO immunobiological (display,definition) VALUES ('Meningo AC', 'Vacina meningocócica AC');
INSERT INTO immunobiological (display,definition) VALUES ('VFA', 'Vacina febre amarela');
INSERT INTO immunobiological (display,definition) VALUES ('BCG', 'Vacina BCG');
INSERT INTO immunobiological (display,definition) VALUES ('SACROT', 'Soro anticrotálico');
INSERT INTO immunobiological (display,definition) VALUES ('Hib', 'Vacina Hib');
INSERT INTO immunobiological (display,definition) VALUES ('VR', 'Vacina raiva embrião de galinha');
INSERT INTO immunobiological (display,definition) VALUES ('IGHV', 'Imunoglobulina humana antivaricela');
INSERT INTO immunobiological (display,definition) VALUES ('IGHHB', 'Imunoglobulina humana anti-hepatite B');
INSERT INTO immunobiological (display,definition) VALUES ('VPP23', 'Vacina pneumo 23');
INSERT INTO immunobiological (display,definition) VALUES ('VIP', 'Vacina polio injetável');
INSERT INTO immunobiological (display,definition) VALUES ('IGHR', 'Imunoglobulina humana antirrábica');
INSERT INTO immunobiological (display,definition) VALUES ('SCR', 'Vacina sarampo, caxumba, rubéola');
INSERT INTO immunobiological (display,definition) VALUES ('dT', 'Vacina difteria e tétano adulto');
INSERT INTO immunobiological (display,definition) VALUES ('VPC10', 'Vacina pneumo 10');
INSERT INTO immunobiological (display,definition) VALUES ('SLATRO', 'Soro latrodectus');
INSERT INTO immunobiological (display,definition) VALUES ('VOP', 'Vacina polio oral');
INSERT INTO immunobiological (display,definition) VALUES ('PENTA acelular', 'Vacina penta acelular (DTPa/VIP/Hib)');
INSERT INTO immunobiological (display,definition) VALUES ('FTp', 'Vacina febre tifóide');
INSERT INTO immunobiological (display,definition) VALUES ('SALOXO', 'Soro antiloxoscélico (trivalente)');
INSERT INTO immunobiological (display,definition) VALUES ('SALONO', 'Soro antilonômico');
INSERT INTO immunobiological (display,definition) VALUES ('INF3', 'Vacina influenza trivalente');
INSERT INTO immunobiological (display,definition) VALUES ('VAR', 'Vacina varicela');
INSERT INTO immunobiological (display,definition) VALUES ('HA', 'Vacina hepatite A');
INSERT INTO immunobiological (display,definition) VALUES ('SR', 'Vacina sarampo, rubéola');
INSERT INTO immunobiological (display,definition) VALUES ('Vero', 'Vacina raiva em cultivo celular vero');
INSERT INTO immunobiological (display,definition) VALUES ('SBOTULTRI', 'Soro antibotulínico (trivalente)');
INSERT INTO immunobiological (display,definition) VALUES ('Tetra', 'Vacina DTP/Hib');
INSERT INTO immunobiological (display,definition) VALUES ('Pncc7V', 'Vacina pneumocócica 7V');
INSERT INTO immunobiological (display,definition) VALUES ('MenC', 'Vacina meningo C');
INSERT INTO immunobiological (display,definition) VALUES ('PENTA', 'Vacina penta (DTP/HepB/Hib)');
INSERT INTO immunobiological (display,definition) VALUES ('HEXA', 'Vacina hexa (DTPa/HepB/VIP/Hib)');
INSERT INTO immunobiological (display,definition) VALUES ('H1N1', 'Vacina Influenza H1N1');
INSERT INTO immunobiological (display,definition) VALUES ('ROTA', 'Vacina rotavírus');
INSERT INTO immunobiological (display,definition) VALUES ('DTP', 'Vacina DTP');
INSERT INTO immunobiological (display,definition) VALUES ('DTPa', 'Vacina DTPa infantil');
INSERT INTO immunobiological (display,definition) VALUES ('DILSRC', 'Diluente para vacina sarampo, caxumba, rubéola');
INSERT INTO immunobiological (display,definition) VALUES ('DILVFA', 'Diluente para vacina febre amarela');
INSERT INTO immunobiological (display,definition) VALUES ('DILHib', 'Diluente para vacina haemophilus influenzae B');
INSERT INTO immunobiological (display,definition) VALUES ('Fta', 'Vacina febre tifóide (atenuada)');
INSERT INTO immunobiological (display,definition) VALUES ('DilMengAC', 'Diluente meningo AC');
INSERT INTO immunobiological (display,definition) VALUES ('DILSR', 'Diluente para vacina sarampo, rubéola');
INSERT INTO immunobiological (display,definition) VALUES ('DILVAR', 'Diluente para vacina varicela');
INSERT INTO immunobiological (display,definition) VALUES ('HepAinf', 'Vacina hepatite A infantil');
INSERT INTO immunobiological (display,definition) VALUES ('SCRV', 'Vacina sarampo, caxumba, rubéola e varicela');
INSERT INTO immunobiological (display,definition) VALUES ('dTpa', 'Vacina dTpa adulto');
INSERT INTO immunobiological (display,definition) VALUES ('TETRA acelular', 'Vacina DTPa/VIP');
INSERT INTO immunobiological (display,definition) VALUES ('VPC13', 'Vacina pneumo 13');
INSERT INTO immunobiological (display,definition) VALUES ('HPV2', 'Vacina HPV bivalente');
INSERT INTO immunobiological (display,definition) VALUES ('TT', 'Vacina toxóide tetânico');
INSERT INTO immunobiological (display,definition) VALUES ('HAeHBped', 'Hepatite AeB (pediátrica)');
INSERT INTO immunobiological (display,definition) VALUES ('HAeHB', 'Vacina hepatite AeB (uso adulto)');
INSERT INTO immunobiological (display,definition) VALUES ('FLU ID', 'Vacina influenza ID');
INSERT INTO immunobiological (display,definition) VALUES ('ROTA5', 'Vacina rotavírus pentavalente');
INSERT INTO immunobiological (display,definition) VALUES ('MEN BC', 'Vacina meningocócica B/C');
INSERT INTO immunobiological (display,definition) VALUES ('HPV4', 'Vacina HPV quadrivalente');
INSERT INTO immunobiological (display,definition) VALUES ('HPV Bi', 'Vacina HPV bivalente');
INSERT INTO immunobiological (display,definition) VALUES ('SABOT', 'Soro antibotulínico AB (bivalente)');
INSERT INTO immunobiological (display,definition) VALUES ('Sarampo', 'Vacina sarampo');
INSERT INTO immunobiological (display,definition) VALUES ('Rubeola', 'Vacina rubéola');
INSERT INTO immunobiological (display,definition) VALUES ('Gripe Sazonal', 'Vacina gripe');
INSERT INTO immunobiological (display,definition) VALUES ('Quadrupla Viral', 'Vacina quádrupla viral');
INSERT INTO immunobiological (display,definition) VALUES ('MenACWY', 'Vacina meningo ACWY');
INSERT INTO immunobiological (display,definition) VALUES ('COLERA', 'Vacina cólera');
INSERT INTO immunobiological (display,definition) VALUES ('VHZ', 'Vacina herpes-zóster');
INSERT INTO immunobiological (display,definition) VALUES ('INF4', 'Vacina influenza tetravalente');
INSERT INTO immunobiological (display,definition) VALUES ('MenB', 'Vacina meningo B');
INSERT INTO immunobiological (display,definition) VALUES ('DILBCG', 'Diluente para vacina BCG');
INSERT INTO immunobiological (display,definition) VALUES ('DILVRvero', 'Diluente para vacina raiva cultivo celulas vero');
INSERT INTO immunobiological (display,definition) VALUES ('DILMenC', 'Diluente para vacina meningo C');
INSERT INTO immunobiological (display,definition) VALUES ('Dengue', 'Vacina dengue');
INSERT INTO immunobiological (display,definition) VALUES ('HEPAad', 'Vacina hepatite A adulto');
INSERT INTO immunobiological (display,definition) VALUES ('VFA-F', 'Vacina febre amarela fracionada');
INSERT INTO immunobiological (display,definition) VALUES ('COVID-19 ASTRAZENECA/FIOCRUZ - COVISHIELD', 'Vacina Covid-19 ASTRAZENECA/FIOCRUZ - COVISHIELD, recombinante');
INSERT INTO immunobiological (display,definition) VALUES ('COVID-19 SINOVAC/BUTANTAN - CORONAVAC', 'Vacina COVID-19 SINOVAC/BUTANTAN - CORONAVAC, inativada');
INSERT INTO immunobiological (display,definition) VALUES ('COVID-19 PFIZER - COMIRNATY', 'Vacina COVID-19 PFIZER - COMIRNATY, RNAm');
INSERT INTO immunobiological (display,definition) VALUES ('COVID-19 JANSSEN - Ad26.COV2.S', 'Vacina COVID-19 JANSSEN - Ad26.COV2.S, recombinante');
INSERT INTO immunobiological (display,definition) VALUES ('COVID-19 ASTRAZENECA - ChAdOx1-S', 'Vacina COVID-19 ASTRAZENECA - ChAdOx1-S, recombinante');
INSERT INTO immunobiological (display,definition) VALUES ('DILSCRV', 'Diluente para vacina sarampo, caxumba, rubéola e varicela');
INSERT INTO immunobiological (display,definition) VALUES ('DILVR', 'Diluente para vacina raiva cultivo embrião de galinha');
INSERT INTO immunobiological (display,definition) VALUES ('VRvero', 'Vacina raiva cultivo celulas vero');
INSERT INTO immunobiological (display,definition) VALUES ('HPV9', 'Vacina HPV nonavalente');
INSERT INTO immunobiological (display,definition) VALUES ('DILCOV', 'Diluente Covid-19');
INSERT INTO immunobiological (display,definition) VALUES ('COVID-19 GAMALEYA - SPUTNIK V', 'Vacina COVID-19 GAMALEYA - SPUTNIK V recombinante');
INSERT INTO immunobiological (display,definition) VALUES ('COVID-19 BHARAT - COVAXIN', 'Vacina Covid-19 COVID-19 BHARAT - COVAXIN inativada');
INSERT INTO immunobiological (display,definition) VALUES ('COVID-19 MODERNA', 'Vacina COVID-19 MODERNA RNAm');
INSERT INTO immunobiological (display,definition) VALUES ('COVID-19 SINOVAC - CORONAVAC', 'Vacina COVID-19 SINOVAC - CORONAVAC inativada');
INSERT INTO immunobiological (display,definition) VALUES ('COVID-19 PEDIÁTRICA - PFIZER COMIRNATY', 'Vacina COVID-19 PEDIÁTRICA - PFIZER COMIRNATY RNAm');